### ISSUE TITLE
deterministic = train or = not train?

### ISSUE THREAD

**Issue by davidshen84** [SarthakYadav/jax-mae#2]
https://github.com/SarthakYadav/jax-mae/blob/main/mae/models/mlp.py#L38

I think it should be `deterministic=not train`.

**Comment by SarthakYadav** [comment]
Hi @davidshen84 ,

Yes, that's correct, it should be `deterministic=not train`. Mlp dropout is not used by default, so we're not messing things up big time for now.

**Comment by SarthakYadav** [comment]
Fixed in commit [5f95617](https://github.com/SarthakYadav/jax-mae/commit/5f956176e982c0a01c8e23ccea2e82cc6419b274). Thanks for reporting this issue, closing it now.
